from abc import ABC, abstractmethod

class BaseLLMClient(ABC):
    """
    Abstract Base Class for all LLM clients.

    This class defines the standard interface for interacting with
    different Language Model APIs. It ensures that all concrete
    client implementations adhere to a consistent contract.
    """

    @abstractmethod
    def generate(self, prompt: str, **kwargs) -> str:
        """
        Generates a response from the LLM based on the given prompt.

        This method must be implemented by all subclasses.

        Args:
            prompt (str): The input text to send to the LLM.
            **kwargs: Additional provider-specific parameters (e.g., temperature, max_tokens).

        Returns:
            str: The text response generated by the LLM.
        """
        pass

    def get_provider_name(self) -> str:
        """
        Returns the name of the LLM provider.
        Can be overridden by subclasses if a different name is desired.
        """
        return self.__class__.__name__
